<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>io.github.photowey</groupId>
        <artifactId>riff-middleware-database</artifactId>
        <version>${reversion}</version>
    </parent>

    <artifactId>riff-middleware-database-persistence-mybatis</artifactId>
    <name>riff-middleware-database-persistence-mybatis</name>
    <description>middleware-database persistence-mybatis module for riff.jv</description>

    <properties>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-spring-boot3-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-extension</artifactId>
        </dependency>
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-jsqlparser</artifactId>
        </dependency>

        <dependency>
            <groupId>org.mybatis</groupId>
            <artifactId>mybatis-typehandlers-jsr310</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.datatype</groupId>
            <artifactId>jackson-datatype-jsr310</artifactId>
        </dependency>

        <dependency>
            <groupId>io.github.photowey</groupId>
            <artifactId>riff-middleware-database-orm</artifactId>
        </dependency>
        <dependency>
            <groupId>io.github.photowey</groupId>
            <artifactId>riff-middleware-database-meta</artifactId>
        </dependency>

        <dependency>
            <groupId>io.github.photowey</groupId>
            <artifactId>riff-infras-model</artifactId>
        </dependency>
    </dependencies>

    <build>
        <plugins>
        </plugins>
    </build>

</project>
